import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';
import{command,events,lease,pair,session,snapshot}from'./api';import{PdfViewer}from'./pdf';import'./styles.css';
import{ResearchSuite}from'./research';import{WorkspaceBoard}from'./workspace';import{ToolsSuite}from'./tools';
import{SourceSidebar}from'./sources';
type Tab='documents'|'notes'|'workspace'|'research'|'tools';
function App(){const[ready,setReady]=useState(false),[error,setError]=useState(''),[manual,setManual]=useState(''),[needsPairing,setNeedsPairing]=useState(false),[project,setProject]=useState<any>(),[sources,setSources]=useState<any[]>([]),[selected,setSelected]=useState<any>(),[annotations,setAnnotations]=useState<any[]>([]),[tab,setTab]=useState<Tab>('documents'),[editing,setEditing]=useState(false),[version,setVersion]=useState(0),[sourceDrawer,setSourceDrawer]=useState(false);
 const load=async()=>{const[p,s]=await Promise.all([snapshot<any>('project'),snapshot<any[]>('sources')]);const next=Array.isArray(s.data)?s.data:[];setProject(p.data);setSources(next);if(selected){const current=next.find(x=>x.id===selected.id);if(current)setSelected(current)}};
 const finishPairing=async(token:string)=>{await pair(token,navigator.userAgent.includes('Mobile')?'Mobile browser':'Web browser');history.replaceState(null,'','/');try{await lease('acquire');setEditing(true)}catch{setEditing(false)}await load();setNeedsPairing(false);setError('');setReady(true)};
 useEffect(()=>{(async()=>{try{await session();await load();setReady(true)}catch(first:any){const token=new URLSearchParams(location.hash.split('?')[1]||'').get('token');if(!token){if(first?.status===401){setNeedsPairing(true);setError('Enter the current manual code, or scan the QR code in Papyrus Settings.')}else setError(`Connected to Papyrus, but project sync failed: ${first.message}`);return}try{await finishPairing(token)}catch(e:any){setError(`Pairing failed: ${e.message}`)}}})()},[]);
 useEffect(()=>{if(!ready)return;const ws=events(e=>{if(['sources','project','annotations','workspaces'].includes(e.domain)){setVersion(v=>v+1);load().catch(()=>{})}});return()=>ws.close()},[ready]);
 useEffect(()=>{if(!editing)return;const id=setInterval(()=>lease('heartbeat').catch(()=>setEditing(false)),20000);return()=>clearInterval(id)},[editing]);
 const open=async(s:any)=>{setSelected(s);setTab('documents');if(s.source_type==='pdf'){const a=await snapshot<any[]>('annotations',`?source_id=${encodeURIComponent(s.id)}`);setAnnotations(a.data)}};
 const gain=async()=>{try{await lease('acquire');setEditing(true)}catch(e:any){setError(e.message)}};
 if(!ready)return <main className="pair"><div className="brand">P</div><h1>Papyrus</h1><p>{error||'Connecting securely to your laptop…'}</p>{needsPairing?<form className="manualPair" onSubmit={async e=>{e.preventDefault();try{setError('Pairing…');await finishPairing(manual.trim())}catch(problem:any){setError(`Pairing failed: ${problem.message}`)}}}><input autoFocus inputMode="numeric" autoComplete="one-time-code" maxLength={6} pattern="[0-9]{6}" aria-label="Six digit pairing code" placeholder="000000" value={manual} onChange={e=>setManual(e.target.value.replace(/\D/g,''))}/><button disabled={manual.length!==6}>Pair browser</button></form>:error&&<button onClick={()=>location.reload()}>Retry connection</button>}</main>;
 return <div className="app"><header><div className="brand small">P</div><div><b>Papyrus</b><small>{project?.name||'No project open'}</small></div><button className="mobileSourcesButton" onClick={()=>setSourceDrawer(true)}>▤ Sources <b>{sources.length}</b></button><span/><button className={editing?'live':''} onClick={editing?async()=>{await lease('release');setEditing(false)}:gain}>{editing?'Editing':'View only'}</button></header>{sourceDrawer&&<button className="drawerBackdrop" aria-label="Close sources" onClick={()=>setSourceDrawer(false)}/>}<SourceSidebar sources={sources} selected={selected} editing={editing} onOpen={open} onRefresh={load} mobileOpen={sourceDrawer} onClose={()=>setSourceDrawer(false)}/><main className="content">{tab==='documents'&&<Documents source={selected} annotations={annotations} refresh={()=>open(selected)}/>} {tab==='notes'&&<Notes version={version} sources={sources} editing={editing}/>} {tab==='workspace'&&<WorkspaceBoard version={version} editing={editing}/>} {tab==='research'&&<ResearchSuite editing={editing} sources={sources}/>} {tab==='tools'&&<ToolsSuite editing={editing} sources={sources}/>}</main><nav>{(['documents','notes','workspace','research','tools']as Tab[]).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}><i>{({documents:'▤',notes:'✎',workspace:'◇',research:'✦',tools:'⌘'}as any)[t]}</i>{t}</button>)}</nav>{error&&<div className="toast" onClick={()=>setError('')}>{error}</div>}</div>}
function Documents({source,annotations,refresh}:any){if(!source)return <Empty title="Open a source" body="Choose a PDF or video from the source list."/>;if(source.source_type==='video')return <div className="video"><video controls src={`/api/v1/source/${source.id}/media`}/><h2>{source.filename}</h2></div>;return <PdfViewer source={source} annotations={annotations} refresh={refresh}/>}
function Notes({version,sources,editing}:any){const[notes,setNotes]=useState<any[]>([]);useEffect(()=>{snapshot<any[]>('notes').then(x=>setNotes(x.data))},[version]);return <Panel title="Notes" subtitle="Highlights and notes across this project"><div className="cards">{notes.map(n=><article key={n.id}><small>{sources.find((s:any)=>s.id===n.source_id)?.filename} · page {(n.page_num??0)+1}</small><blockquote>{n.text_content}</blockquote><p>{n.content||'No note text'}</p>{editing&&<div><button onClick={async()=>{const note=prompt('Edit note',n.content)||'';await command('annotations','update',{annot_id:n.id,note});const x=await snapshot<any[]>('notes');setNotes(x.data)}}>Edit</button><button className="danger" onClick={async()=>{await command('annotations','delete',{annot_id:n.id});setNotes(notes.filter(x=>x.id!==n.id))}}>Delete</button></div>}</article>)}</div></Panel>}
function Panel({title,subtitle,children}:any){return <section className="panel"><div className="panelhead"><h1>{title}</h1><p>{subtitle}</p></div>{children}</section>}function Empty({title,body}:any){return <div className="empty"><div>⌁</div><h2>{title}</h2><p>{body}</p></div>}
class ErrorBoundary extends React.Component<{children:React.ReactNode},{message:string}>{state={message:''};static getDerivedStateFromError(error:Error){return{message:error?.message||'Unexpected browser error'}}componentDidCatch(error:Error){console.error('Papyrus web interface error',error)}render(){if(this.state.message)return <main className="pair"><div className="brand">P</div><h1>Interface recovery</h1><p>The web interface hit an error: {this.state.message}</p><button onClick={()=>location.reload()}>Reload Papyrus</button></main>;return this.props.children}}
createRoot(document.getElementById('root')!).render(<ErrorBoundary><App/></ErrorBoundary>);
