import {useEffect,useRef,useState} from 'react';
import * as pdfjs from 'pdfjs-dist';
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';
import {command} from './api';
pdfjs.GlobalWorkerOptions.workerSrc=workerUrl;

type Props={source:any;annotations:any[];refresh:()=>void};
export function PdfViewer({source,annotations,refresh}:Props){
 const [doc,setDoc]=useState<any>();const [scale,setScale]=useState(1.25);const [selection,setSelection]=useState<any>();const [query,setQuery]=useState('');const [hitCount,setHitCount]=useState<number>();
 useEffect(()=>{let alive=true;pdfjs.getDocument({url:`/api/v1/source/${source.id}/media`}).promise.then(d=>alive&&setDoc(d));return()=>{alive=false}},[source.id]);
 const capture=(page:number,container:HTMLDivElement,viewport:any)=>{const sel=window.getSelection();if(!sel||sel.isCollapsed||!sel.toString().trim())return;const base=container.getBoundingClientRect();const rects=[...sel.getRangeAt(0).getClientRects()].filter(r=>r.width>1&&r.height>1).map(r=>{const a=viewport.convertToPdfPoint(r.left-base.left,r.top-base.top);const b=viewport.convertToPdfPoint(r.right-base.left,r.bottom-base.top);return[Math.min(a[0],b[0]),Math.min(a[1],b[1]),Math.max(a[0],b[0]),Math.max(a[1],b[1])]});setSelection({page_num:page,rects,text:sel.toString().trim()})};
 const highlight=async(color:string)=>{if(!selection)return;const note=prompt('Optional note')||'';await command('annotations','create',{source_id:source.id,...selection,color,note});window.getSelection()?.removeAllRanges();setSelection(undefined);refresh()};
 return <section className="viewer"><div className="viewerbar"><strong>{source.filename}</strong><input aria-label="Search PDF" placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={async e=>{if(e.key==='Enter'){const r=await fetch(`/api/v1/source/${source.id}/search?q=${encodeURIComponent(query)}`).then(x=>x.json());setHitCount(r.data?.length||0)}}}/>{hitCount!==undefined&&<small>{hitCount} hits</small>}<span/><button onClick={()=>setScale(s=>Math.max(.5,s-.15))}>−</button><b>{Math.round(scale*100)}%</b><button onClick={()=>setScale(s=>Math.min(3,s+.15))}>＋</button></div>{selection&&<div className="selectionbar">Highlight selection <button className="yellow" onClick={()=>highlight('#ffe500')}/><button className="green" onClick={()=>highlight('#20cc66')}/><button className="purple" onClick={()=>highlight('#b366ff')}/><button onClick={()=>setSelection(undefined)}>Cancel</button></div>}<div className="pages">{doc&&Array.from({length:doc.numPages},(_,i)=><PdfPage key={`${i}-${scale}`} doc={doc} index={i} scale={scale} annotations={annotations.filter(a=>a.page_num===i)} onSelect={capture}/>)}</div></section>
}
function PdfPage({doc,index,scale,annotations,onSelect}:any){const canvas=useRef<HTMLCanvasElement>(null);const pageRoot=useRef<HTMLDivElement>(null);const textRoot=useRef<HTMLDivElement>(null);const [viewport,setViewport]=useState<any>();
 useEffect(()=>{let cancelled=false;doc.getPage(index+1).then(async(page:any)=>{const view=page.getViewport({scale});setViewport(view);const cvs=canvas.current;if(!cvs||cancelled)return;const ratio=devicePixelRatio||1;cvs.width=view.width*ratio;cvs.height=view.height*ratio;cvs.style.width=`${view.width}px`;cvs.style.height=`${view.height}px`;await page.render({canvasContext:cvs.getContext('2d')!,viewport:view,transform:ratio===1?undefined:[ratio,0,0,ratio,0,0]}).promise;const content=await page.getTextContent();const root=textRoot.current;if(!root)return;root.innerHTML='';for(const item of content.items as any[]){const tx=pdfjs.Util.transform(view.transform,item.transform);const span=document.createElement('span');span.textContent=item.str;span.style.left=`${tx[4]}px`;span.style.top=`${tx[5]-Math.hypot(tx[2],tx[3])}px`;span.style.fontSize=`${Math.hypot(tx[2],tx[3])}px`;span.style.transform=`scaleX(${item.width*scale/Math.max(1,span.textContent.length*Math.hypot(tx[2],tx[3])*.5)})`;root.append(span)}});return()=>{cancelled=true}},[doc,index,scale]);
 const parse=(raw:string)=>{const nums=(raw||'').match(/-?\d+(?:\.\d+)?/g)?.map(Number)||[];return nums.slice(0,4)};
 return <div className="page" ref={pageRoot} style={{width:viewport?.width,height:viewport?.height}} onMouseUp={()=>viewport&&pageRoot.current&&onSelect(index,pageRoot.current,viewport)}><canvas ref={canvas}/><div className="textContent" ref={textRoot}/><div className="textlayer">{annotations.map((a:any)=>{const r=parse(a.rect_coords);if(r.length<4||!viewport)return null;const box=viewport.convertToViewportRectangle(r);return <i key={a.id} title={a.content} style={{left:Math.min(box[0],box[2]),top:Math.min(box[1],box[3]),width:Math.abs(box[2]-box[0]),height:Math.abs(box[3]-box[1]),background:a.color||'#ffe500'}}/>})}</div></div>}
