import {useEffect,useMemo,useState} from 'react';
import {command,events,snapshot} from './api';

type Props={editing:boolean;sources:any[]};
type Mode='chat'|'brainstorm'|'analysis'|'agent'|'history';

export function ResearchSuite({editing,sources}:Props){
 const[mode,setMode]=useState<Mode>('chat');const[messages,setMessages]=useState<any[]>([]);const[text,setText]=useState('');const[busy,setBusy]=useState(false);const[catalog,setCatalog]=useState<any>({templates:[]});const[jobs,setJobs]=useState<any[]>([]);const[agent,setAgent]=useState<any>();const[sourceId,setSourceId]=useState('');const[templateId,setTemplateId]=useState('');const[error,setError]=useState('');
 const target=mode==='brainstorm'?'brainstorm_dock':'chat_dock';
 const refreshHistory=()=>snapshot<any[]>('history',`?query=${target}`).then(x=>setMessages(x.data));
 const refreshJobs=()=>snapshot<any[]>('jobs').then(x=>setJobs(x.data));
 useEffect(()=>{snapshot<any>('ai').then(x=>{setCatalog(x.data);setTemplateId(x.data.templates?.[0]?.id||'')});refreshHistory();refreshJobs();snapshot<any>('research').then(x=>setAgent(x.data)).catch(()=>{});const ws=events(e=>{if(e.domain==='workflow'){const p=e.payload?.[1]||{};if(p.data?.chunk&&mode!=='history')setMessages(m=>[...m,{role:'assistant',content:p.data.chunk}]);if(['completed','failed'].includes(e.payload?.[0])){setBusy(false);refreshHistory();refreshJobs()}}if(e.domain==='research')setAgent(e.payload?.[1]?.session||e.payload?.[1])});return()=>ws.close()},[]);
 useEffect(()=>{if(!sourceId&&sources[0])setSourceId(sources[0].id)},[sources]);
 useEffect(()=>{if(mode==='chat'||mode==='brainstorm')refreshHistory()},[mode]);
 const send=async()=>{if(!text.trim())return;const query=text.trim();setText('');setMessages(m=>[...m,{role:'user',content:query}]);setBusy(true);setError('');try{await command('ai','run',{blueprint_id:mode==='brainstorm'?'Brainstorming':'Chat - Universal Agent',initial_state:mode==='brainstorm'?{query}:{user_query:query},target_id:target})}catch(e:any){setBusy(false);setError(e.message)}};
 const startAnalysis=async()=>{setError('');try{await command('analysis','run',{source_id:sourceId,template_id:templateId});setBusy(true);setMode('history')}catch(e:any){setError(e.message)}};
 const startAgent=async()=>{try{setAgent((await command<any>('research','start',{goal:text})).data);setText('')}catch(e:any){setError(e.message)}};
 return <section className="panel"><div className="panelhead"><h1>Research Assistant</h1><p>Local models, project context, auditable workflows, and human checkpoints</p></div><div className="subnav">{(['chat','brainstorm','analysis','agent','history']as Mode[]).map(item=><button className={mode===item?'active':''} onClick={()=>setMode(item)} key={item}>{item}</button>)}</div>{error&&<p className="inlineError">{error}</p>}
 {(mode==='chat'||mode==='brainstorm')&&<><div className="chat">{messages.map((m,i)=><article className={m.role==='user'?'user':''} key={i}><small>{m.role==='user'?'You':'Papyrus'}</small><p>{m.content}</p></article>)}</div><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={mode==='chat'?'Ask about your project…':'Explore a thesis, connection, or research direction…'}/><button disabled={!editing||busy} onClick={send}>{busy?'Working…':'Send'}</button></div></>}
 {mode==='analysis'&&<div className="formPage"><h2>Document Analysis</h2><label>Source<select value={sourceId} onChange={e=>setSourceId(e.target.value)}>{sources.filter(s=>s.source_type==='pdf').map(s=><option value={s.id} key={s.id}>{s.filename}</option>)}</select></label><label>Analysis template<select value={templateId} onChange={e=>setTemplateId(e.target.value)}>{(catalog.templates||[]).map((t:any)=><option value={t.id} key={t.id}>{t.title||t.name||t.id}</option>)}</select></label><button disabled={!editing||!sourceId||!templateId||busy} onClick={startAnalysis}>Run analysis on laptop</button></div>}
 {mode==='agent'&&<div className="formPage"><h2>Research Agent</h2>{agent?<><p><b>Goal:</b> {agent.goal}</p><p><b>Status:</b> {agent.status}</p><pre>{JSON.stringify(agent.checkpoints||agent.artifacts||[],null,2)}</pre><div className="toolActions"><button disabled={!editing} onClick={()=>command('research','plan',{})}>Continue planning</button><button disabled={!editing} onClick={async()=>setAgent((await command<any>('research','reset',{})).data)}>Reset</button></div></>:<><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="What should the research agent accomplish?"/><button disabled={!editing||!text.trim()} onClick={startAgent}>Start agent</button></>}</div>}
 {mode==='history'&&<div className="history"><div className="sectionTitle"><h2>Process History</h2><button onClick={refreshJobs}>Refresh</button></div>{jobs.map(job=><article key={job.id}><b>{job.name}</b><span>{job.status}</span><small>{job.type}</small>{job.status?.toLowerCase().includes('running')&&<button disabled={!editing} onClick={()=>command('ai','cancel',{job_id:job.id})}>Cancel</button>}</article>)}</div>}</section>
}
