import {useEffect,useMemo,useState} from 'react';
import {command,snapshot,upload} from './api';

export function SourceSidebar({sources,selected,editing,onOpen,onRefresh,mobileOpen=false,onClose=()=>{}}:{sources:any[];selected:any;editing:boolean;onOpen:(s:any)=>void;onRefresh:()=>Promise<void>;mobileOpen?:boolean;onClose?:()=>void}){
 const[filter,setFilter]=useState('');const[busy,setBusy]=useState(false);const[tags,setTags]=useState<any[]>([]);
 useEffect(()=>{snapshot<any[]>('tags').then(x=>setTags(x.data))},[]);
 const visible=useMemo(()=>sources.filter(s=>s.filename.toLowerCase().includes(filter.toLowerCase())||s.tags?.some((t:any)=>t.name.toLowerCase().includes(filter.toLowerCase()))),[sources,filter]);
 const add=async(file?:File)=>{if(!file)return;setBusy(true);try{await upload(file);await onRefresh()}finally{setBusy(false)}};
 const rename=async(source:any)=>{const name=prompt('New filename',source.filename)?.trim();if(!name||name===source.filename)return;await command('sources','rename',{source_id:source.id,name});await onRefresh()};
 const remove=async(source:any)=>{if(!confirm(`Remove “${source.filename}” from this project? The original file will not be deleted.`))return;await command('sources','remove',{source_id:source.id});await onRefresh()};
 const manageTags=async(source:any)=>{const entered=prompt('Comma-separated tags',source.tags?.map((t:any)=>t.name).join(', ')||'');if(entered===null)return;const names=[...new Set(entered.split(',').map(x=>x.trim()).filter(Boolean))];let catalog=[...tags];for(const name of names){if(!catalog.some(t=>t.name.toLowerCase()===name.toLowerCase()))catalog=(await command<any[]>('tags','create',{name,color:'#b366ff'})).data}const wanted=new Set(names.map(x=>x.toLowerCase()));for(const tag of catalog){const has=source.tags?.some((t:any)=>t.id===tag.id);const should=wanted.has(tag.name.toLowerCase());if(has!==should)await command('tags','assign',{target_type:'document',target_id:source.id,tag_id:tag.id,assigned:should})}setTags(catalog);await onRefresh()};
 return <aside className={mobileOpen?'mobileOpen':''}><div className="sourceHeading"><h3>Sources <small>{sources.length}</small></h3><button className="closeSources" aria-label="Close sources" onClick={onClose}>×</button></div><label className="upload">{busy?'Importing…':'＋ Add source'}<input type="file" accept="application/pdf,video/*" disabled={!editing||busy} onChange={e=>add(e.target.files?.[0])}/></label><input className="sourceFilter" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter sources or tags"/><div className="sourceList">{visible.length?visible.map(source=><div className={`sourceRow ${selected?.id===source.id?'active':''}`} key={source.id}><button className="sourceOpen" onClick={()=>{onOpen(source);onClose()}}><i>{source.source_type==='video'?'▶':'▤'}</i><span>{source.filename}<small>{source.source_type}{source.tags?.length?` · ${source.tags.map((t:any)=>t.name).join(', ')}`:''}</small></span></button>{editing&&<div className="sourceActions"><button title="Manage tags" onClick={()=>manageTags(source)}>#</button><button title="Rename" onClick={()=>rename(source)}>✎</button><button title="Remove from project" onClick={()=>remove(source)}>×</button></div>}</div>):<p className="sourceEmpty">No sources are currently registered in this project.</p>}</div></aside>
}
