import {useEffect,useMemo,useRef,useState} from 'react';
import {command,newId,snapshot} from './api';

export function WorkspaceBoard({version,editing}:{version:number;editing:boolean}){
 const[boards,setBoards]=useState<any[]>([]);const[model,setModel]=useState<any>();const[selected,setSelected]=useState<string[]>([]);const[dirty,setDirty]=useState(false);const boardRef=useRef<HTMLDivElement>(null);const drag=useRef<any>(null);
 const load=async(id?:number)=>{const list=(await snapshot<any[]>('workspaces')).data;setBoards(list);const boardId=id||list?.[0]?.id||list?.[0]?.workspace_id||1;setModel((await snapshot<any>('workspace',`?workspace_id=${boardId}`)).data);setSelected([]);setDirty(false)};
 useEffect(()=>{load()},[version]);
 const change=(fn:(value:any)=>any)=>{setModel((m:any)=>fn(m));setDirty(true)};
 const move=(id:string,x:number,y:number)=>change(m=>({...m,nodes:m.nodes.map((n:any)=>n.id===id?{...n,x:Math.max(10,x),y:Math.max(10,y)}:n)}));
 const addNode=()=>{const id=newId(),text=prompt('Node text')?.trim();if(!text)return;change(m=>({...m,nodes:[...m.nodes,{id,quote:'',note:text,color:'#b366ff',is_custom:true,x:40,y:40,width:210,height:100,workspace_id:m.workspace_id,node_origin:'human',is_verified:1,original_text:text,node_type_id:'workspace.node.text',entity_type:'entity.text',entity_properties:{text},entity_state:{is_verified:true,origin:'human'}}]}))};
 const connect=()=>{if(selected.length!==2)return;change(m=>({...m,edges:[...m.edges,{id:newId(),source:selected[0],target:selected[1],label:prompt('Connection label')||'',color:'#9f7aea',weight:2,relation_type:'relation.basic',evidence_ids:[],relation_properties:{},relation_state:{is_verified:true}}]}));setSelected([])};
 const remove=()=>{change(m=>({...m,nodes:m.nodes.filter((n:any)=>!selected.includes(n.id)),edges:m.edges.filter((e:any)=>!selected.includes(e.source)&&!selected.includes(e.target)),deleted_node_ids:[...(m.deleted_node_ids||[]),...selected]}));setSelected([])};
 const byId=useMemo(()=>Object.fromEntries((model?.nodes||[]).map((n:any)=>[n.id,n])),[model]);
 const startNode=(event:React.PointerEvent,n:any)=>{if(!editing){setSelected(s=>s.includes(n.id)?s.filter(x=>x!==n.id):[...s,n.id]);return}event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);drag.current={id:n.id,pointer:event.pointerId,startX:event.clientX,startY:event.clientY,nodeX:n.x||10,nodeY:n.y||10,moved:false}};
 const dragNode=(event:React.PointerEvent)=>{const value=drag.current;if(!value||value.pointer!==event.pointerId)return;const dx=event.clientX-value.startX,dy=event.clientY-value.startY;if(Math.abs(dx)+Math.abs(dy)>4)value.moved=true;if(value.moved)move(value.id,value.nodeX+dx,value.nodeY+dy)};
 const finishNode=(event:React.PointerEvent)=>{const value=drag.current;if(!value||value.pointer!==event.pointerId)return;if(!value.moved)setSelected(s=>s.includes(value.id)?s.filter(x=>x!==value.id):[...s,value.id]);drag.current=null};
 const center=()=>{const nodes=model?.nodes||[];if(!nodes.length)return;const left=Math.max(0,Math.min(...nodes.map((n:any)=>n.x||0))-30),top=Math.max(0,Math.min(...nodes.map((n:any)=>n.y||0))-30);boardRef.current?.scrollTo({left,top,behavior:'smooth'})};
 return <section className="panel workspacePanel"><div className="panelhead"><h1>Workspace</h1><p>Drag nodes to move them. Drag empty space to pan.</p></div><div className="workspacebar">{boards.map((w:any)=><button onClick={()=>load(w.id||w.workspace_id)} key={w.id||w.workspace_id}>{w.name||`Board ${w.id}`}</button>)}{editing&&<button onClick={async()=>{const result=await command<any>('workspaces','create',{name:prompt('Board name')||'New board'});await load(result.data.workspace_id)}}>＋ Board</button>}{editing&&<button onClick={addNode}>＋ Node</button>}<button onClick={center}>Center</button><button disabled={!editing||selected.length!==2} onClick={connect}>Connect</button><button disabled={!editing||!selected.length} onClick={remove}>Delete</button><button disabled={!editing||!dirty} onClick={async()=>{setModel((await command<any>('workspaces','sync',model)).data);setDirty(false)}}>Save</button></div><div className="board" ref={boardRef}><div className="boardSurface"><svg>{(model?.edges||[]).map((e:any)=>{const a:any=byId[e.source],b:any=byId[e.target];if(!a||!b)return null;return <g key={e.id}><line x1={(a.x||0)+105} y1={(a.y||0)+50} x2={(b.x||0)+105} y2={(b.y||0)+50}/><text x={((a.x||0)+(b.x||0))/2+105} y={((a.y||0)+(b.y||0))/2+45}>{e.label}</text></g>})}</svg>{model?.nodes?.map((n:any)=><article className={selected.includes(n.id)?'selected':''} onPointerDown={e=>startNode(e,n)} onPointerMove={dragNode} onPointerUp={finishNode} onPointerCancel={()=>{drag.current=null}} key={n.id} style={{left:n.x||10,top:n.y||10,borderColor:n.color}}><b>{n.quote||n.note||'Untitled node'}</b><small>{n.entity_type||n.node_type_id}</small></article>)}</div></div></section>
}
